<?php

use Illuminate\Database\Seeder;

class StocksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = array(
            array('ticker'=>'PETR4','name'=>'PETROBRAS PN','main_activity'=>'Petróleo. Gás e Energia'),
array('ticker'=>'VALE3','name'=>'VALE ON','main_activity'=>'Mineração'),
array('ticker'=>'ITUB4','name'=>'ITAUUNIBANCO PN','main_activity'=>'A Sociedade Tem por Objeto A Atividade Bancária em Todas as Modalidades Autorizadas. Inclusive A de Operações de Câmbio.'),
array('ticker'=>'BBAS3','name'=>'BRASIL ON','main_activity'=>'Banco Múltiplo'),
array('ticker'=>'BOVA11','name'=>'ISHARES BOVA CI','main_activity'=>''),
array('ticker'=>'PETR3','name'=>'PETROBRAS ON','main_activity'=>'Petróleo. Gás e Energia'),
array('ticker'=>'MGLU3','name'=>'MAGAZ LUIZA ON','main_activity'=>'Somos Uma Rede Varejista e Atuamos com Foco na Comercialização de Bens Duráveis no Brasil.'),
array('ticker'=>'BBDC4','name'=>'BRADESCO PN','main_activity'=>'Prática de Operações Bancárias em Geral. Inclusive Câmbio'),
array('ticker'=>'ABEV3','name'=>'AMBEV S/A ON','main_activity'=>'Fabricação e Distribuição de Cervejas. Refrigerantes e Bebidas Não Carbonatadas e Não Alcoólicas.'),
array('ticker'=>'B3SA3','name'=>'B3','main_activity'=>'Principais Atividades: Administrar Mercados Organizados de Títulos e Valores Mobiliários; Prestar Serviços de Registro. Compensação e Liquidação e de Suporte à Operações de Financiamento'),
array('ticker'=>'ITSA4','name'=>'ITAUSA PN','main_activity'=>'Gestão de Participações Societárias (holding)'),
array('ticker'=>'SUZB3','name'=>'SUZANO PAPEL ON','main_activity'=>'Indústria e Comércio de Papel e Celulose'),
array('ticker'=>'GGBR4','name'=>'GERDAU PN','main_activity'=>'Participação e Administração'),
array('ticker'=>'USIM5','name'=>'USIMINAS PNA','main_activity'=>'Venda de Produtos Siderúrgicos. como Chapas Grossas. Laminados A Quente. A Frio. Placas. Galvanizados. entre Outros.'),
array('ticker'=>'KLBN11','name'=>'KLABIN S/A UNT','main_activity'=>'Empresa Brasileira de Base Florestal. Produtora de Papéis e Cartões para Embalagens. Embalagens de Papelão Ondulado e Sacos Industriais. Além de Ser Recicladora e Produtora de Toras para Serrarias.'),
array('ticker'=>'BRFS3','name'=>'BRF SA ON','main_activity'=>'Holding Operacional'),
array('ticker'=>'RAIL3','name'=>'RUMO S.A. ON','main_activity'=>'Prestar Serviços de Transporte de Cargas Através dos Modais Ferroviário e Rodoviário. Dentre Outros. Isoladamente ou Combinados entre Si de Forma Intermodal ou Multimodal. entre Outros.'),
array('ticker'=>'CVCB3','name'=>'CVC BRASIL ON','main_activity'=>'Serviços de Turismo. Compreendendo A Intermediação. Individualmente ou na Forma Agregada. de Passagens Aéreas. Transporte Terrestre. Reservas de Hotéis. Passagens de Cruzeiros Marítimos. entre Outros.'),
array('ticker'=>'GOAU4','name'=>'GERDAU MET PN','main_activity'=>'Participação e Administração'),
array('ticker'=>'RENT3','name'=>'LOCALIZA ON','main_activity'=>'Aluguel de Carros e Gestão de Frotas'),
array('ticker'=>'LREN3','name'=>'LOJAS RENNER ON','main_activity'=>'Loja de Departamentos (Comércio Varejista)'),
array('ticker'=>'BRDT3','name'=>'PETROBRAS BR','main_activity'=>'Distribuição e Venda de Álcool Carburante. Biodísel. Gasolina e Demais Derivados de Petróleo. Incluindo Lubrificantes. Assim como Gás Natural.'),
array('ticker'=>'CSAN3','name'=>'COSAN ON','main_activity'=>'Produção de Açúcar. Etanol e Cogeração de Energia. Distribuição de Combustíveis.produção e Distribuição de Lubrificantes.tranporte e Carregamento de Açúcar. Operador de Terras e Distribuição de Gás.'),
array('ticker'=>'FIBR3','name'=>'FIBRIA ON','main_activity'=>''),
array('ticker'=>'BBSE3','name'=>'BBSEGURIDADE ON','main_activity'=>'Participação no Capital Social de Outras Sociedades. que Tenham por Atividade Operações de Seguros. Resseguros. Previdências Complementar ou Capitalização.'),
array('ticker'=>'CSNA3','name'=>'SID NACIONAL ON','main_activity'=>'A Companhia Siderúrgica Nacional Atua Nos Setores de Mineração. Siderurgia. Logística. Cimento e Energia.'),
array('ticker'=>'LAME4','name'=>'LOJAS AMERIC PN','main_activity'=>'Comércio em Geral. Inclusive Supermercado e Lanchonete. Lojas de Conveniência. no Varejo e no Atacado. Através de Lojas e Depósitos. de Quaisquer Mercadorias. Bem como A Realização de Serviços.'),
array('ticker'=>'IRBR3','name'=>'IRBBRASIL RE ON','main_activity'=>'Operações de Resseguro e Retrocessão'),
array('ticker'=>'BRML3','name'=>'BR MALLS PAR ON','main_activity'=>'Holding'),
array('ticker'=>'ESTC3','name'=>'ESTACIO PART ON','main_activity'=>'A Estácio Participações S.A e as Sociedades de Propósito Específico por Elas Controladas Desenvolvem. Principalmente. Atividades de Ensino Superior nas Modalidades Presencial e A Distância.'),
array('ticker'=>'CMIG4','name'=>'CEMIG PN','main_activity'=>'Concessionária de Serviço Público de Energia Elétrica.'),
array('ticker'=>'QUAL3','name'=>'QUALICORP ON','main_activity'=>'Prestação de Serviços e Gestão de Benefícios de Assistência à Saúde.'),
array('ticker'=>'VIVT4','name'=>'TELEF BRASIL PN','main_activity'=>'Prestação de Serviços Públicos de Telecomunicações'),
array('ticker'=>'CIEL3','name'=>'CIELO ON','main_activity'=>'Empresa Prestadora de Serviços de Adquirência e Meios de Pagamento.'),
array('ticker'=>'PCAR4','name'=>'P.ACUCAR-CBD PN','main_activity'=>'Comércio Varejista'),
array('ticker'=>'UGPA3','name'=>'ULTRAPAR ON','main_activity'=>'Distribuição de Combustíveis. Químicos e Armazenagem para Granéis Líquidos'),
array('ticker'=>'JBSS3','name'=>'JBS ON','main_activity'=>''),
array('ticker'=>'KROT3','name'=>'KROTON ON','main_activity'=>'A Companhia Tem por Objeto A Participação. como Sócia ou Acionista. em Sociedades que Explorem A Administração de Atividades de Educação.'),
array('ticker'=>'BTOW3','name'=>'B2W DIGITAL ON','main_activity'=>'Comércio Varejista e Atacadista em Geral de Quaisquer Bens e Serviços Através de Diversos Meios. em Especial da Internet. sem Restrição A Outros Meios.'),
array('ticker'=>'EMBR3','name'=>'EMBRAER ON','main_activity'=>'Produção de Aerovanes'),
array('ticker'=>'CCRO3','name'=>'CCR SA ON','main_activity'=>'Prestadora de Serviços Públicos por Meio de Concessões Rodoviária. Metroviária e Aeroportuária. Além de Prestação de Serviços de Meio de Pagamentos e Outros.'),
array('ticker'=>'NATU3','name'=>'NATURA ON','main_activity'=>'Comércio Atacadista de Comércio e Produtos de Perfumaria'),
array('ticker'=>'VVAR11','name'=>'VIAVAREJO UNT','main_activity'=>''),
array('ticker'=>'BBDC3','name'=>'BRADESCO ON','main_activity'=>'Prática de Operações Bancárias em Geral. Inclusive Câmbio'),
array('ticker'=>'RADL3','name'=>'RAIADROGASIL ON','main_activity'=>'Comércio de Produtos Farmacêuticos. Perfumarias e Afins'),
array('ticker'=>'BRAP4','name'=>'BRADESPAR PN','main_activity'=>'Participação como Sócia ou Acionista de Outras Sociedades.'),
array('ticker'=>'TAEE11','name'=>'TAESA UNT','main_activity'=>'Transmissão de Energia Elétrica.'),
array('ticker'=>'WEGE3','name'=>'WEG ON','main_activity'=>'A Weg Sa É Uma Sociedade de Participação Não Operacional (holding) Etambém Sociedade de Comando do Grupo Weg.'),
array('ticker'=>'EQTL3','name'=>'EQUATORIAL ON','main_activity'=>'Empresa Holding com Atuação no Setor Elétrico'),
array('ticker'=>'UNIP6','name'=>'UNIPAR PNB','main_activity'=>'Atuar no Setor de Soda. Cloro e Derivados. Podendo Participar como Sócia ou Acionista de Outras Sociedades. Direta ou Indiretamente. Inclusive por Meio de Fundos de Investimentos.'),
array('ticker'=>'RAPT4','name'=>'RANDON PART PN','main_activity'=>'Indústria e Comércio de Veíc. Automotores e Rebocados para A Movimentação e o de Transporte de Materiais; de Implem para o Transp Rodoviário e Ferroviário e de Aparelhos Mecânicos. Peças'),
array('ticker'=>'SANB11','name'=>'SANTANDER BR UNT','main_activity'=>'Banco Múltiplo com Carteira Comercial'),
array('ticker'=>'SBSP3','name'=>'SABESP ON','main_activity'=>'Abastecimento de Água. Esgotamento Sanitário. Drenagem e Manejo de Águas Pluviais Urbanas. Limpeza Urbana. Manejo de Resíduos Sólidos e Energia.'),
array('ticker'=>'BRKM5','name'=>'BRASKEM PNA','main_activity'=>'(1) Produção de Produtos Químicos e Petroquímicos Básicos. Resinas Termoplásticas. Utilidades e Energia Elétrica; (2) Prestação de Serviços Industriais; e (3) Participação em Outras Sociedades.'),
array('ticker'=>'IGTA3','name'=>'IGUATEMI ON','main_activity'=>'Empresa Full Service no Setor de Shopping Centers. Suas Atividades Englobam A Concepção. o Planejamento. o Desenvolvimento e A Administração de Shopping Centers Regionais e Complexos Imobiliários.'),
array('ticker'=>'HAPV3','name'=>'HAPVIDA ON','main_activity'=>'Participação. como Sócia ou Acionista. em Outras Empresas. Predominantemente de Assistência Médica. Bem como A Realização de Investimentos Diretos e A Exploração de Atividades de Prestação de Serviços'),
array('ticker'=>'ENBR3','name'=>'ENERGIAS BR ON','main_activity'=>'Área de Negócios: Geração. Distribuição. Transmissão e Comercialização de Energia Elétrica'),
array('ticker'=>'CYRE3','name'=>'CYRELA REALT ON','main_activity'=>'Incorporação Imobiliária'),
array('ticker'=>'ELET3','name'=>'ELETROBRAS ON','main_activity'=>'Empresa Holding de Geração. Transmissão e Distribuição de Energia'),
array('ticker'=>'MULT3','name'=>'MULTIPLAN ON','main_activity'=>'Administração de Shopping Centers'),
array('ticker'=>'HYPE3','name'=>'HYPERMARCAS ON','main_activity'=>'Fabricacão de Medicamentos Alopáticos para Uso Humano'),
array('ticker'=>'TIMP3','name'=>'TIM PART S/A ON','main_activity'=>''),
array('ticker'=>'CSMG3','name'=>'COPASA ON','main_activity'=>'Prestar Serviços de Saneamento.'),
array('ticker'=>'ELPL3','name'=>'ELETROPAULO ON','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'ECOR3','name'=>'ECORODOVIAS ON','main_activity'=>'Exploração Direta ou Indireta de Negócios de Concessão de Obras e Serviços Públicos e Organização Logísitica do Transporte de Carga.'),
array('ticker'=>'ELET6','name'=>'ELETROBRAS PNB','main_activity'=>'Empresa Holding de Geração. Transmissão e Distribuição de Energia'),
array('ticker'=>'GOLL4','name'=>'GOL PN','main_activity'=>'Gestão de Participação Societária'),
array('ticker'=>'SAPR11','name'=>'SANEPAR','main_activity'=>'Exploração de Serviços Públicos e de Sistemas Privados de Abastecimento de Água. de Coleta. Remoção e Destinação Final de Efluentes e Resíduos Sólidos Domésticos e Industriais e Seus Subprodutos.'),
array('ticker'=>'SMLS3','name'=>'SMILES ON','main_activity'=>'Programa de Fidelização que Reúne. em Único Ambiente ou Plataforma. Diversos Parceiros E/ou Outros Programas de Fidelização. Permitindo que Seus Clientes Possam Acumular Bem como Trocar Milhas.'),
array('ticker'=>'FLRY3','name'=>'FLEURY ON','main_activity'=>'(i) A Prestação de Serviços Médicos e Medicina Diagnóstica. (ii) A Consultoria. Assessoria. Cursos e Palestras na Área da Saúde. Bem como A Prestação de Serviços que Visem A Promoção de Saúde'),
array('ticker'=>'BOVV11','name'=>'IT NOW IBOV CI','main_activity'=>''),
array('ticker'=>'MRVE3','name'=>'MRV ON','main_activity'=>'Atividades de Incorporação e Construçãoatividades de Logística'),
array('ticker'=>'GFSA3','name'=>'GAFISA ON','main_activity'=>''),
array('ticker'=>'DAGB33','name'=>'DUFRY AG DR3','main_activity'=>'Adquirir. Deter. Administrar Continuamente. Vender e Financiar Participações em Companhias de Todos os Tipos na Suíça e no Exterior.'),
array('ticker'=>'AZUL4','name'=>'AZUL PN','main_activity'=>'Transporte e Logística'),
array('ticker'=>'MYPK3','name'=>'IOCHP-MAXION ON','main_activity'=>'Fabricação e Comercialização de Produtos do Setor Automotivo e Equipamentos Ferroviários.'),
array('ticker'=>'SLCE3','name'=>'SLC AGRICOLA ON','main_activity'=>'Produção e Comercialização de Algodão. Soja. Milho. Café. entre Outros.'),
array('ticker'=>'TEND3','name'=>'TENDA ON','main_activity'=>''),
array('ticker'=>'PSSA3','name'=>'PORTO SEGURO ON','main_activity'=>'Gestão de Participações Societárias (holding)'),
array('ticker'=>'POMO4','name'=>'MARCOPOLO PN','main_activity'=>''),
array('ticker'=>'LIGT3','name'=>'LIGHT S/A ON','main_activity'=>'Participação em Sociedades P/ Exploração Serviços de Energia Elétrica'),
array('ticker'=>'EGIE3','name'=>'ENGIE BRASIL ON','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'HGTX3','name'=>'CIA HERING ON','main_activity'=>'Confecção de Artigos do Vestuário e Acessórios'),
array('ticker'=>'BIDI11','name'=>'BANCO INTER UNT','main_activity'=>'Banco Múltiplo com Carteira de Crédito. Financiamento. Investimento e Câmbio.'),
array('ticker'=>'TGMA3','name'=>'TEGMA ON','main_activity'=>'Prestação de Serviços de Logística para A Indústria Automotiva. Gerenciamento de Estoques e Pátios. Atividades de Armazém Geral. Pdi. Dentre Outras.'),
array('ticker'=>'BRSR6','name'=>'BANRISUL PNB','main_activity'=>'Banco Múltiplo Atuante nas Carteiras Comercial. Crédito. Financiamento e Investimento. Crédito Imobiliário. Desenvolvimento e Arrendamento Mercantil e de Investimentos.'),
array('ticker'=>'MDIA3','name'=>'M.DIASBRANCO ON','main_activity'=>'Produção e Comercialização de Biscoitos. Massas. Farinha de Trigo e Farelo. Margarinas e Gorduras. Bolos. Snacks. Mistura para Bolos e Torradas.'),
array('ticker'=>'CRFB3','name'=>'CARREFOUR BR ON','main_activity'=>'Comércio Varejista e Atacadista de Mercadorias em Geral; Carga e Descarga; Correspondentes de Instituições Financeiras; Atividades de Teleatendimento; Serviços de Alimentação entre Outros'),
array('ticker'=>'BKBR3','name'=>'BK BRASIL','main_activity'=>'Prestação de Serviços de Operação e Assessoria A Restaurantes'),
array('ticker'=>'DTEX3','name'=>'DURATEX ON','main_activity'=>'Fabricação. Comércio. Importação e Exportação de Produtos Derivados de Madeira. de Produtos de Metais e Materiais Cerâmicos'),
array('ticker'=>'ENGI11','name'=>'ENERGISA UNT','main_activity'=>'Sociedade de Participações em Outras Empresas. Predominantemente em Distribuidoras de Energia Elétrica.'),
array('ticker'=>'CPLE6','name'=>'COPEL PNB','main_activity'=>'Geração. Transmissão. Comercialização e Distribuição de Energia Elétrica'),
array('ticker'=>'TUPY3','name'=>'TUPY ON','main_activity'=>'Produtos Fundidos para A Industria Automobilística / Conexões em Ferro Fundido para Aplicações em Redes Hidráulicas e de Gás / Granalhas e Perfis'),
array('ticker'=>'CAML3','name'=>'CAMIL ON','main_activity'=>'Industrialização e Comercialização de Arroz. Feijão. Pescados e Açúcar.'),
array('ticker'=>'TRPL4','name'=>'TRAN PAULIST PN','main_activity'=>'Transmissão de Energia Elétrica'),
array('ticker'=>'ARZZ3','name'=>'AREZZO CO ON','main_activity'=>'O Principal Ramo de Atividade da Companhia É A Industrialização e A Comercialização de Artigos de Couro e de Plástico em Geral. Incluindo Sapatos e Artigos de Vestuário.'),
array('ticker'=>'QGEP3','name'=>'QGEP PART ON','main_activity'=>'Participação em Sociedades que Se Dediquem à Exploração. Produção Ecomercialização de Petróleo. Gás Natural e Seus Derivados. Seja como Sócio Ouacionista ou Outras Formas de Associações.'),
array('ticker'=>'CESP6','name'=>'CESP PNB','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'LINX3','name'=>'LINX ON','main_activity'=>''),
array('ticker'=>'CPFE3','name'=>'CPFL ENERGIA ON','main_activity'=>'Gestão de Participações Societárias (holdings)'),
array('ticker'=>'SMTO3','name'=>'SAO MARTINHO ON','main_activity'=>'Fabricação e Comércio de Açúcar. Álcool e Derivados.'),
array('ticker'=>'VLID3','name'=>'VALID ON','main_activity'=>'Impressão de Documentos de Segurança.'),
array('ticker'=>'SULA11','name'=>'SUL AMERICA UNT','main_activity'=>'A Sul América S.A. É Uma Sociedade de Participação e Suas Controladas Atuam Nos Setores de Seguros. Previdência Complementar. Administração de Recursos. Capitalização e Assistência à Saúde.'),
array('ticker'=>'MRFG3','name'=>'MARFRIG ON','main_activity'=>'Produção e Distribuição de Alimentos à Base de Carne Bovina. Suína. Ovina e Avícola. In Natura. Elaborados e Processados. Couros Semi-Terminados e Terminados. Além de Outros Produtos Alimentícios.'),
array('ticker'=>'MPLU3','name'=>'MULTIPLUS ON','main_activity'=>'A Multiplus Atua com o Conceito de Rede de Empresas e Programas de Fidelização. por Meio Desta Rede. os Consumidores Podem Acumular e Resgatar Pontos Nos Estabelecimentos Parceiros.'),
array('ticker'=>'OIBR3','name'=>'OI ON','main_activity'=>''),
array('ticker'=>'MOVI3','name'=>'MOVIDA ON','main_activity'=>'Aluguel de Carros e Gestão de Frotas'),
array('ticker'=>'BIDI4','name'=>'BANCO INTER PN','main_activity'=>'Banco Múltiplo com Carteira de Crédito. Financiamento. Investimento e Câmbio.'),
array('ticker'=>'EZTC3','name'=>'EZTEC ON','main_activity'=>'(a) Incorporação e Comercialização de Empreendimentos Imobiliários de Qualquer Natureza. (b) Administração e Locação de Imóveis Prórpios. (c) Loteamento de Terrenos. (d) Construção de Condomínios ...'),
array('ticker'=>'DIRR3','name'=>'DIRECIONAL ON','main_activity'=>'Incorporação. Construção e Comercialização de Imóveis Próprios ou de Terceiros e Prestação de Serviços de Engenharia.'),
array('ticker'=>'TIET11','name'=>'AES TIETE E UNT','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'TOTS3','name'=>'TOTVS ON','main_activity'=>'Prestação de Serviços de Consultoria. Assessoria e Desenvolvimento de Sistemas Informatizados (software). Atividades de Pesquisa e Inovação Tecnológica. Prestação de Serviços Relacionados à Gestão.'),
array('ticker'=>'SHOW3','name'=>'TIME FOR FUN ON','main_activity'=>'Atuação no Setor de Entretenimento ao Vivo. Através da Operação de Casas de Espetáculos e de Bilheterias. da Comercialização de Alimentos. Bebidas e Produtos Promocionais e da Negociação de Patrocínio'),
array('ticker'=>'CMIG3','name'=>'CEMIG ON','main_activity'=>'Concessionária de Serviço Público de Energia Elétrica.'),
array('ticker'=>'ODPV3','name'=>'ODONTOPREV ON','main_activity'=>'Operadora de Planos Odontológicos'),
array('ticker'=>'GNDI3','name'=>'INTERMEDICA ON','main_activity'=>'Prestação de Serviços de Assistência à Saúde e Odontológica.'),
array('ticker'=>'ITUB3','name'=>'ITAUUNIBANCO ON','main_activity'=>'A Sociedade Tem por Objeto A Atividade Bancária em Todas as Modalidades Autorizadas. Inclusive A de Operações de Câmbio.'),
array('ticker'=>'SEER3','name'=>'SER EDUCA ON','main_activity'=>'Desenvolvimento e A Administração de Atividades e Instituições no Setor de Educação e Outrasáreas Associadas; Administração de Bens e Negócios Próprios; e Participação em Outrassociedades.'),
array('ticker'=>'WIZS3','name'=>'WIZ S.A. ON','main_activity'=>'Corretagem de Seguros de Todos os Ramos. Assessoria e Consultoria na Área de Seguros em Geral. Intermediação e Desenvolvimento de Soluções em Negócios. sem Especificaçãodefinida. Dentre Outros.'),
array('ticker'=>'LEVE3','name'=>'METAL LEVE ON','main_activity'=>'Industria e Comércio de Peças e Componentes para Motores A Combustão'),
array('ticker'=>'PRIO3','name'=>'PETRORIO ON','main_activity'=>'Constitui Objeto da Companhia A Participação em Outras Sociedades como Sócia. Acionista ou Quotista. Independentemente de Sua Atividade.'),
array('ticker'=>'CGAS5','name'=>'COMGAS PNA','main_activity'=>'Setor de Atividade: Utilidade Pública: Distribuição de Gás Natural Canalizado.'),
array('ticker'=>'BEEF3','name'=>'MINERVA ON','main_activity'=>'Um dos Líderes da América Latina na Produção e Comercialização de Carne In Natura. Boi Vivo e Seus Derivados e que Atua Também Nos Segmentos de Processamento de Carne Bovina. Suína e de Aves.'),
array('ticker'=>'BPAC11','name'=>'BTGP BANCO UNT','main_activity'=>'A Companhia e Suas Controladas Formam Um Grupo de Prestação de Serviços Financeiros Sediado no Brasil. Atuando como Banco Múltiplo. com Carteira de Investimento. Nos Termos da Legislação Aplicável.'),
array('ticker'=>'OIBR4','name'=>'OI PN','main_activity'=>''),
array('ticker'=>'VULC3','name'=>'VULCABRAS ON','main_activity'=>'Representantes Comerciais e Agentes do Comércio de Têxteis. Vestuário. Calçados e Artigos de Viagem.'),
array('ticker'=>'LAME3','name'=>'LOJAS AMERIC ON','main_activity'=>'Comércio em Geral. Inclusive Supermercado e Lanchonete. Lojas de Conveniência. no Varejo e no Atacado. Através de Lojas e Depósitos. de Quaisquer Mercadorias. Bem como A Realização de Serviços.'),
array('ticker'=>'ABCB4','name'=>'ABC BRASIL PN','main_activity'=>'O Banco Tem por Objeto A Prática de Operações Ativas. Passivas e Acessórias Inerentes às Respectivas Carteiras Autorizadas pelo Banco Central do Brasil.'),
array('ticker'=>'CTGP34','name'=>'CITIGROUP DRN','main_activity'=>''),
array('ticker'=>'PEPB34','name'=>'PEPSICO INC DRN','main_activity'=>''),
array('ticker'=>'FESA4','name'=>'FERBASA PN','main_activity'=>'Fabricação e Comercialização dos Diversos Tipos de Ferroligas'),
array('ticker'=>'ALSC3','name'=>'ALIANSCE ON','main_activity'=>''),
array('ticker'=>'KNCR11','name'=>'FII KINEA RI','main_activity'=>''),
array('ticker'=>'MAGG3','name'=>'MAGNESITA SA ON','main_activity'=>'Mineração. Produção e Comercialização de Extensa Linha de Materiais Refratários.'),
array('ticker'=>'BRPR3','name'=>'BR PROPERT ON','main_activity'=>'Compra. Venda e Incorp. de Imóveis Comerciais Prontos ou A Construir; Admin de Imóveis Próprios ou de Terceiros; Arrendamento. Exploração Com. Locação Sub-Locação de Imóveis Comerciais Própr. e Outros'),
array('ticker'=>'ANIM3','name'=>'ANIMA ON','main_activity'=>'Administração. Direta ou Indireta. de Atividade de Instituições de 3º e 4º Graus. Educação Profissional.'),
array('ticker'=>'PARD3','name'=>'IHPARDINI ON','main_activity'=>'Prestação de Serviços de Medicina Diagnóstica.'),
array('ticker'=>'ALUP11','name'=>'ALUPAR UNT','main_activity'=>'A Participação em Outras Sociedades Atuantes Nos Setores de Energia e Infra-Estrutura. no Brasil ou no Exterior; A Geração. Transformação. Transporte. A Distribuiçãoe o Comércio de Energia.'),
array('ticker'=>'GUAR3','name'=>'GUARARAPES ON','main_activity'=>'Confecções de Roupas e Tecidos em Geral.'),
array('ticker'=>'ALPA4','name'=>'ALPARGATAS PN','main_activity'=>'Indústria e Comércio de Calçados e Artigos Esportivos'),
array('ticker'=>'HBOR3','name'=>'HELBOR ON','main_activity'=>'Incorporação de Imoveis'),
array('ticker'=>'GRND3','name'=>'GRENDENE ON','main_activity'=>'Fabricação de Calçados em Geral'),
array('ticker'=>'BBPO11','name'=>'FII BB PRGII','main_activity'=>''),
array('ticker'=>'VISC11','name'=>'FII VINCI SC','main_activity'=>''),
array('ticker'=>'BRCR11','name'=>'FII BC FUND','main_activity'=>''),
array('ticker'=>'TSLA34','name'=>'TESLA INC DRN','main_activity'=>''),
array('ticker'=>'DMMO3','name'=>'DOMMO ON','main_activity'=>'A Companhia Terá por Objeto A Exploração. Produção e Comercialização de Petróleo e Seus Derivados. Gás Natural e Outros Hidrocarbonetos Fluidos.'),
array('ticker'=>'BBRK3','name'=>'BR BROKERS ON','main_activity'=>'Participação em Sociedades que Atuem no Setor Imobiliário.'),
array('ticker'=>'GGRC11','name'=>'FII GGRCOVEP','main_activity'=>''),
array('ticker'=>'UNIP3','name'=>'UNIPAR ON','main_activity'=>'Atuar no Setor de Soda. Cloro e Derivados. Podendo Participar como Sócia ou Acionista de Outras Sociedades. Direta ou Indiretamente. Inclusive por Meio de Fundos de Investimentos.'),
array('ticker'=>'KNRI11','name'=>'FII KINEA','main_activity'=>''),
array('ticker'=>'ENEV3','name'=>'ENEVA ON','main_activity'=>'Empresa de Recursos Naturais e de Geração de Energia Elétrica. Integração Vertical na Geração de Energia Elétrica.'),
array('ticker'=>'HGLG11','name'=>'FII CSHG LOG','main_activity'=>''),
array('ticker'=>'AMAR3','name'=>'LOJAS MARISA ON','main_activity'=>'Comércio Varejista de Artigos do Vestuário e Acessórios. Prestação de Serviços de Correspondente Bancário. Intermediação de Negócios e Congêneres. Atuação como Representante de Seguros.'),
array('ticker'=>'STBP3','name'=>'SANTOS BRP ON','main_activity'=>'A Companhia Tem por Objeto A Exploração Comercial de Instalação Portuária Através de Operações com Contêineres. Carga Geral ou Afins e A Participação em Outras Sociedades.'),
array('ticker'=>'SAPR4','name'=>'SANEPAR PN','main_activity'=>'Exploração de Serviços Públicos e de Sistemas Privados de Abastecimento de Água. de Coleta. Remoção e Destinação Final de Efluentes e Resíduos Sólidos Domésticos e Industriais e Seus Subprodutos.'),
array('ticker'=>'OMGE3','name'=>'OMEGA GER ON','main_activity'=>'Participação. Direta ou por Meio de Joint Venture (parceria). Consórcio ou Qualquer Outra Sociedade. em Ativos de Energia Elétrica que Já Tenham Atingido A Fase Operacional'),
array('ticker'=>'COWC34','name'=>'COSTCO DRN','main_activity'=>''),
array('ticker'=>'MEAL3','name'=>'IMC S/A ON','main_activity'=>'Setor de Varejo de Alimentação'),
array('ticker'=>'PTBL3','name'=>'PORTOBELLO ON','main_activity'=>'Industrialização e Comercialização de Revestimentos Cerâmicos'),
array('ticker'=>'BOAC34','name'=>'BANK AMERICA DRN','main_activity'=>''),
array('ticker'=>'GBIO33','name'=>'BIOTOSCANA DR3','main_activity'=>''),
array('ticker'=>'PMAM3','name'=>'PARANAPANEMA ON','main_activity'=>'Metalurgia do Cobre e Suas Ligas'),
array('ticker'=>'PIBB11','name'=>'IT NOW PIBB CI','main_activity'=>''),
array('ticker'=>'VIVT3','name'=>'TELEF BRASIL ON','main_activity'=>'Prestação de Serviços Públicos de Telecomunicações'),
array('ticker'=>'TCSA3','name'=>'TECNISA ON','main_activity'=>'Incorporação. Compra e Venda de Imóveis Prontos e A Construir A Locação e Administração de Bens Imóveis. Construção de Imóveis e A Prestação de Serviço de Consultoria Imobiliaria.'),
array('ticker'=>'CARD3','name'=>'CSU CARDSYST ON','main_activity'=>'Terceirização em Administração e Processamento de Meios Eletrónicos de Pagamento. Infraestrutura e Gestão em Terceirização de Contact Center. Desenvolvimento e Gestão Operacional de Programas Market'),
array('ticker'=>'SHUL4','name'=>'SCHULZ PN','main_activity'=>'Indústria Metalúrgica'),
array('ticker'=>'RLOG3','name'=>'COSAN LOG ON','main_activity'=>'Administração. Direta ou Indireta. de Participações Societárias em Empresas do Setor de Infraestrutura.'),
array('ticker'=>'XPML11','name'=>'FII XP MALLS','main_activity'=>''),
array('ticker'=>'ITSA3','name'=>'ITAUSA ON','main_activity'=>'Gestão de Participações Societárias (holding)'),
array('ticker'=>'SAAG11','name'=>'FII SANT AGE','main_activity'=>''),
array('ticker'=>'CZLT33','name'=>'COSAN LTD DR3','main_activity'=>'Produção de Açúcar. Etanol e Cogeração de Energia. Distribuição de Combustíveis. Produção Ee Distribuição de Lubrificantes. Transporte e Carregamento de Açúcar e Operador Logístico'),
array('ticker'=>'SMAL11','name'=>'ISHARES SMAL CI','main_activity'=>''),
array('ticker'=>'LCAM3','name'=>'LOCAMERICA ON','main_activity'=>'A Companhia Tem por Objeto A Atividade de Locação de Veículos Nacionais e Importados com ou sem Motorista.'),
array('ticker'=>'XBOV11','name'=>'CAIXAETFXBOV CI','main_activity'=>''),
array('ticker'=>'TPIS3','name'=>'TRIUNFO PART ON','main_activity'=>'A Triunfo Atua Nos Segmentos de Concessões Rodoviárias. Aeroportuária. Geração de Energia e Administração Portuária. A Situação do Emissor É de Recuperação Extrajudicial.'),
array('ticker'=>'JSRE11','name'=>'FII JS REAL','main_activity'=>''),
array('ticker'=>'FIGS11','name'=>'FII GEN SHOP','main_activity'=>''),
array('ticker'=>'AGRO3','name'=>'BRASILAGRO ON','main_activity'=>'Empresa de Desenvolvimento Agropecuario'),
array('ticker'=>'JHSF3','name'=>'JHSF PART ON','main_activity'=>'Empresa que Investe no Brasil em Negócios Voltados A Atender o Público de Alta Renda. Focada no Desenvolvimento e Administração de Projetos de Shopping Centers. Hotéis e e Restaurantes e Incorporação.'),
array('ticker'=>'LPSB3','name'=>'LOPES BRASIL ON','main_activity'=>'Intermediação na Compra. Venda. Permuta e Locação de Imóveis ou de Direitos e Obrigações A Eles Relativos.'),
array('ticker'=>'AALR3','name'=>'ALLIAR ON','main_activity'=>'Prestação de Serviços de Medicina Diagnóstica.'),
array('ticker'=>'PDGR3','name'=>'PDG REALT ON','main_activity'=>''),
array('ticker'=>'ABCP11','name'=>'FII ABC IMOB','main_activity'=>''),
array('ticker'=>'BCFF11','name'=>'FII BC FFII','main_activity'=>''),
array('ticker'=>'CGRA4','name'=>'GRAZZIOTIN PN','main_activity'=>'Comércio Varejista de Vesturio e Bazar.'),
array('ticker'=>'EVEN3','name'=>'EVEN ON','main_activity'=>'Construção. Incorporação e Loteamento'),
array('ticker'=>'HGRE11','name'=>'FII HG REAL','main_activity'=>''),
array('ticker'=>'HGBS11','name'=>'FII CSHGSHOP','main_activity'=>''),
array('ticker'=>'TBOF11','name'=>'FII TBOFFICE','main_activity'=>''),
array('ticker'=>'IVVB11','name'=>'ISHARE SP500 CI','main_activity'=>''),
array('ticker'=>'RSID3','name'=>'ROSSI RESID ON','main_activity'=>'Compra e Venda de Imóveis. Desmembramento e Loteamento de Terrenos. Incorporação Imobiliária. Construção de Imóveis Destinados à Venda. e A Participação em Outras Sociedades.'),
array('ticker'=>'MILS3','name'=>'MILLS ON','main_activity'=>'Serviços Especiais de Engenharia'),
array('ticker'=>'JSLG3','name'=>'JSL ON','main_activity'=>''),
array('ticker'=>'POMO3','name'=>'MARCOPOLO ON','main_activity'=>''),
array('ticker'=>'SANB4','name'=>'SANTANDER BR PN','main_activity'=>'Banco Múltiplo com Carteira Comercial'),
array('ticker'=>'BRAP3','name'=>'BRADESPAR ON','main_activity'=>'Participação como Sócia ou Acionista de Outras Sociedades.'),
array('ticker'=>'CLSC4','name'=>'CELESC PN','main_activity'=>'Holding do Setor de Energia'),
array('ticker'=>'CPLE3','name'=>'COPEL ON','main_activity'=>'Geração. Transmissão. Comercialização e Distribuição de Energia Elétrica'),
array('ticker'=>'SSBR3','name'=>'SIERRABRASIL ON','main_activity'=>'Planejamento. Desenvolvimento. Implantação e Investimentos na Área Imobiliária. Nomeadamente em Shopping Centers e A Participação em Outras Sociedades E/ou em Fundos de Investimento Imobiliário.'),
array('ticker'=>'NFLX34','name'=>'NETFLIX DRN','main_activity'=>''),
array('ticker'=>'KNIP11','name'=>'FII KINEA IP','main_activity'=>''),
array('ticker'=>'MXRF11','name'=>'FII MAXI REN','main_activity'=>''),
array('ticker'=>'MFII11','name'=>'FII MERITO I','main_activity'=>''),
array('ticker'=>'SGPS3','name'=>'SPRINGS ON','main_activity'=>''),
array('ticker'=>'ROMI3','name'=>'INDS ROMI ON','main_activity'=>'Indústria e Comércio de Máquinas-Ferramenta'),
array('ticker'=>'POSI3','name'=>'POSITIVO TEC ON','main_activity'=>'Fabricação de Computadores.'),
array('ticker'=>'ETER3','name'=>'ETERNIT ON','main_activity'=>'Industrialização e Comercialização de Produtos de Fibrocimento. Cimento. Concreto. Gesso. Produtos de Matéria Plástica. Bem como Outros Materiais de Construção e Respectivos Acessórios.'),
array('ticker'=>'GUAR4','name'=>'GUARARAPES PN','main_activity'=>'Confecções de Roupas e Tecidos em Geral.'),
array('ticker'=>'DIVO11','name'=>'IT NOW IDIV CI','main_activity'=>''),
array('ticker'=>'RBRR11','name'=>'FII RBRHGRAD','main_activity'=>''),
array('ticker'=>'FRAS3','name'=>'FRAS-LE ON','main_activity'=>'Indústria de Autopeças e Materiais de Fricção'),
array('ticker'=>'TRIS3','name'=>'TRISUL ON','main_activity'=>'Incorporadora e Construtora'),
array('ticker'=>'PFRM3','name'=>'PROFARMA ON','main_activity'=>'Profarma Atua na Distribuição de Produtos Farmacêuticos. Higiene Pessoal e Cosméticos. Nos Mais Populosos Estados Brasileiros.'),
array('ticker'=>'FHER3','name'=>'FER HERINGER ON','main_activity'=>'Produção. Comercialização e Distribuição de Fertilizantes. com Atuação Nacional.'),
array('ticker'=>'UBSG34','name'=>'UBS GROUP DRN','main_activity'=>''),
array('ticker'=>'KLBN4','name'=>'KLABIN S/A PN','main_activity'=>'Empresa Brasileira de Base Florestal. Produtora de Papéis e Cartões para Embalagens. Embalagens de Papelão Ondulado e Sacos Industriais. Além de Ser Recicladora e Produtora de Toras para Serrarias.'),
array('ticker'=>'PPLA11','name'=>'PPLA UNT','main_activity'=>'Holding de Companhias que Atuam como Veículos de Investimento.'),
array('ticker'=>'LOGN3','name'=>'LOG-IN ON','main_activity'=>'Empresa de Logistica que Oferece Soluções Integradas para o Transporte de Contêineres por Meio Marítimo. com Ponta Rodoviária. Além dos Serviços Referentes Aos Seus Terminais Portuário e Intermodais.'),
array('ticker'=>'AMZO34','name'=>'AMAZON DRN','main_activity'=>''),
array('ticker'=>'VRTA11','name'=>'FII FATOR VE','main_activity'=>''),
array('ticker'=>'SLED4','name'=>'SARAIVA LIVR PN','main_activity'=>'Edição. Indústria e Comércio de Livros e Publicações em Geral.'),
array('ticker'=>'FVBI11','name'=>'FII VBI 4440','main_activity'=>''),
array('ticker'=>'UCAS3','name'=>'UNICASA ON','main_activity'=>'Indústria. Comércio. Prestação de Serviços. Importação e Exportação de Produtos Relacionados ao Ramo de Mobiliário em Geral. Planejado e Modulado de Madeira. Ferro. Aço. Alumínio e Outros Materiais.'),
array('ticker'=>'CRPG5','name'=>'CRISTAL PNA','main_activity'=>''),
array('ticker'=>'GRLV11','name'=>'FII LOUVEIRA','main_activity'=>''),
array('ticker'=>'XPCM11','name'=>'FII XP MACAE','main_activity'=>''),
array('ticker'=>'SEDU3','name'=>'SOMOS EDUCA ON','main_activity'=>'Edição. Impressão. Publicação. Divulgação e Comercialização no Atacado ou Varejo. de Livros. Apostilas e Publicações de Qualquer Natureza. Voltadas. Principalmente. para A Educação.'),
array('ticker'=>'UNIP5','name'=>'UNIPAR PNA','main_activity'=>'Atuar no Setor de Soda. Cloro e Derivados. Podendo Participar como Sócia ou Acionista de Outras Sociedades. Direta ou Indiretamente. Inclusive por Meio de Fundos de Investimentos.'),
array('ticker'=>'HTMX11','name'=>'FII HOTEL MX','main_activity'=>''),
array('ticker'=>'FOFT11','name'=>'FII CSHGFOFT','main_activity'=>''),
array('ticker'=>'RNGO11','name'=>'FII RIONEGRO','main_activity'=>''),
array('ticker'=>'KEPL3','name'=>'KEPLER WEBER ON','main_activity'=>'Indústria e Comércio de Produtos e Matérias Primas Relacionadas A Metalurgia. Importação e Exportação. Prestação de Serviços. Comércio de Produtos Destinados A Agroindústria.'),
array('ticker'=>'DISB34','name'=>'WALT DISNEY DRN','main_activity'=>''),
array('ticker'=>'EUCA4','name'=>'EUCATEX PN','main_activity'=>'Indústria e Comércio de Chapas de Fibra de Madeira'),
array('ticker'=>'TESA3','name'=>'TERRA SANTA ON','main_activity'=>'- Produção e Comércio de Produtos Vegetais (Soja. Milho e Algodão)- Industrialização e Comércio de Biocombustíveis. Óleo Vegetal e Subprodutos'),
array('ticker'=>'SNSL3','name'=>'SENIOR SOL ON','main_activity'=>'Produção. Desenvolvimento. Licenciamento. Sublicenciamento e Distribuição de Programas de Computador ("software") e Outras Atividades. Conforme Descritas no Estatuto Social da Companhia.'),
array('ticker'=>'VTLT11','name'=>'FII VOT LOG','main_activity'=>''),
array('ticker'=>'TRVC34','name'=>'TRAVELERS DRN','main_activity'=>''),
array('ticker'=>'BRKM3','name'=>'BRASKEM ON','main_activity'=>'(1) Produção de Produtos Químicos e Petroquímicos Básicos. Resinas Termoplásticas. Utilidades e Energia Elétrica; (2) Prestação de Serviços Industriais; e (3) Participação em Outras Sociedades.'),
array('ticker'=>'HFOF11','name'=>'FII HEDGEFOF','main_activity'=>''),
array('ticker'=>'JNJB34','name'=>'JOHNSON DRN','main_activity'=>''),
array('ticker'=>'HGJH11','name'=>'FII CSHGJHSF','main_activity'=>''),
array('ticker'=>'OGXP3','name'=>'OGX PETROLEO ON','main_activity'=>'Participações em Outras Sociedades'),
array('ticker'=>'FIIB11','name'=>'FII INDL BR','main_activity'=>''),
array('ticker'=>'FIND11','name'=>'IT NOW IFNC CI','main_activity'=>''),
array('ticker'=>'GOAU3','name'=>'GERDAU MET ON','main_activity'=>'Participação e Administração'),
array('ticker'=>'MALL11','name'=>'FII MALLS BP','main_activity'=>''),
array('ticker'=>'GGBR3','name'=>'GERDAU ON','main_activity'=>'Participação e Administração'),
array('ticker'=>'TIET4','name'=>'AES TIETE E PN','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'AAPL34','name'=>'APPLE DRN','main_activity'=>''),
array('ticker'=>'HAGA3','name'=>'HAGA S/A ON','main_activity'=>'Industria Metalúrgica - Fab. de Fechaduras P/Construção Civil'),
array('ticker'=>'BRIN3','name'=>'BR INSURANCE ON','main_activity'=>'Participação em Sociedades Corretoras de Seguros e Corretora de Seguros'),
array('ticker'=>'BPAN4','name'=>'BANCO PAN PN','main_activity'=>'Banco Múltiplo com Carteira Comercial'),
array('ticker'=>'COCE5','name'=>'COELCE PNA','main_activity'=>'Distribuição de Energia Elétrica.'),
array('ticker'=>'ARFI11B','name'=>'FII AQUIL RD','main_activity'=>''),
array('ticker'=>'RNEW11','name'=>'RENOVA UNT','main_activity'=>'Geração de Energia por Meio de Fontes Renováveis.'),
array('ticker'=>'SANB3','name'=>'SANTANDER BR ON','main_activity'=>'Banco Múltiplo com Carteira Comercial'),
array('ticker'=>'OFSA3','name'=>'OUROFINO S/A ON','main_activity'=>'Participação em Outras Sociedades que Execerçam Atividades de Desenvolvimento. Fabricação e Comercialização de Produtos Destinados ao Setor de Saúde Animal.'),
array('ticker'=>'SCAR3','name'=>'SAO CARLOS ON','main_activity'=>'Compra e Venda de Imóveis Prontos ou A Construir; Locação de Bens Imóveis; Administração de Empreendimentos Imobiliários Próprios ou de Terceiros; Exercício de Outras Atividades Correlatas; e Outros'),
array('ticker'=>'FAMB11B','name'=>'FII ALMIRANT','main_activity'=>''),
array('ticker'=>'MRCK34','name'=>'MERCK DRN','main_activity'=>''),
array('ticker'=>'CPTS11B','name'=>'FII CAPI SEC','main_activity'=>''),
array('ticker'=>'TECN3','name'=>'TECHNOS ON','main_activity'=>'A Companhia Tem por Objeto Social A Participação em Outras Sociedades. como Sócia ou Acionista. no País ou no Exterior.'),
array('ticker'=>'ESTR3','name'=>'ESTRELA ON','main_activity'=>'Fabricação de Brinquedos e Jogos Recreativos'),
array('ticker'=>'LUPA3','name'=>'LUPATECH ON','main_activity'=>'Fabricante de Equipamentos e Provedor de Serviços para o Setor de Petróleo e Gás.'),
array('ticker'=>'BIIB34','name'=>'BIOGEN DRN','main_activity'=>''),
array('ticker'=>'FCFL11','name'=>'FII CAMPUSFL','main_activity'=>''),
array('ticker'=>'SPTW11','name'=>'FII SP DOWNT','main_activity'=>''),
array('ticker'=>'TRPN3','name'=>'TARPON INV ON','main_activity'=>'Empresa de Participações.'),
array('ticker'=>'KNRE11','name'=>'FII KII REAL','main_activity'=>''),
array('ticker'=>'FEXC11','name'=>'FII EXCELLEN','main_activity'=>''),
array('ticker'=>'GOGL34','name'=>'ALPHABET DRN','main_activity'=>''),
array('ticker'=>'MAXR11','name'=>'FII MAX RET','main_activity'=>''),
array('ticker'=>'MDTC34','name'=>'MEDTRONIC DRN','main_activity'=>''),
array('ticker'=>'CCXC3','name'=>'CCX CARVAO ON','main_activity'=>'Desenvolvimento de Projetos de Carvão na Colómbia. Incluindo. Mas Não Se Limitando A. Pesquisa. Exploração. Lavra. Beneficiamento. Industrialização. Transporte. Exportação e Comércio de Carvão.'),
array('ticker'=>'RBRF11','name'=>'FII RBRALPHA','main_activity'=>''),
array('ticker'=>'JPSA3','name'=>'JEREISSATI','main_activity'=>''),
array('ticker'=>'FJTA4','name'=>'FORJA TAURUS PN','main_activity'=>'Indústria e Comércio de Armas'),
array('ticker'=>'USIM3','name'=>'USIMINAS ON','main_activity'=>'Venda de Produtos Siderúrgicos. como Chapas Grossas. Laminados A Quente. A Frio. Placas. Galvanizados. entre Outros.'),
array('ticker'=>'BERK34','name'=>'BERKSHIRE DRN','main_activity'=>''),
array('ticker'=>'PGCO34','name'=>'PG DRN','main_activity'=>''),
array('ticker'=>'PRML3','name'=>'PRUMO ON','main_activity'=>'Atuação no Setor de Logísitica Portuária.'),
array('ticker'=>'MTSA4','name'=>'METISA PN','main_activity'=>'Fabricação de Máquinas e Equipamentos para A Agricultura e Pecuária. Peças e Acessórios. Exceto para Irrigação.'),
array('ticker'=>'HGCR11','name'=>'FII CSHG CRI','main_activity'=>''),
array('ticker'=>'IRDM11','name'=>'FII IRIDIUM','main_activity'=>''),
array('ticker'=>'CTSH34','name'=>'COGNIZANT DRN','main_activity'=>''),
array('ticker'=>'MBRF11','name'=>'FII MERC BR','main_activity'=>''),
array('ticker'=>'ALZR11','name'=>'FII ALIANZA','main_activity'=>''),
array('ticker'=>'FCXO34','name'=>'FREEPORT DRN','main_activity'=>''),
array('ticker'=>'WSON33','name'=>'WILSON SONS DR3','main_activity'=>'Terminais Portuários. Rebocagem. Offshore. Logística. Agenciamento Marítimo e Estaleiros.'),
array('ticker'=>'MSFT34','name'=>'MICROSOFT DRN','main_activity'=>''),
array('ticker'=>'BCRI11','name'=>'FII BEES CRI','main_activity'=>''),
array('ticker'=>'EDGA11','name'=>'FII GALERIA','main_activity'=>''),
array('ticker'=>'AEFI11','name'=>'FII AESAPAR','main_activity'=>''),
array('ticker'=>'ALMI11','name'=>'FII TORRE AL','main_activity'=>''),
array('ticker'=>'BBFI11B','name'=>'FII BB PROGR','main_activity'=>''),
array('ticker'=>'SBUB34','name'=>'STARBUCKS DRN','main_activity'=>''),
array('ticker'=>'ATOM3','name'=>'ATOMPAR ON','main_activity'=>'Holding de Instituições Não Financeiras.'),
array('ticker'=>'FFCI11','name'=>'FII RIOB RC','main_activity'=>''),
array('ticker'=>'ENMA3B','name'=>'CEMAR','main_activity'=>'Empresa Distribuidora de Energia Elétrica para Todo o Estado do Maranhão.'),
array('ticker'=>'NIKE34','name'=>'NIKE DRN','main_activity'=>''),
array('ticker'=>'VLOE34','name'=>'VALERO ENER DRN','main_activity'=>''),
array('ticker'=>'IBMB34','name'=>'IBM DRN','main_activity'=>''),
array('ticker'=>'BRIV4','name'=>'ALFA INVEST PN','main_activity'=>'A Prática de Todas as Operações Permitidas à Sociedade da Espécie pelas Disposições Legais e Regulamentares que Então Vigorem. Inclusive as de Câmbio. Mas Excetuadas Outras que Dependem de Autoriazaçã'),
array('ticker'=>'BRSR3','name'=>'BANRISUL ON','main_activity'=>'Banco Múltiplo Atuante nas Carteiras Comercial. Crédito. Financiamento e Investimento. Crédito Imobiliário. Desenvolvimento e Arrendamento Mercantil e de Investimentos.'),
array('ticker'=>'TELB4','name'=>'TELEBRAS PN','main_activity'=>'Consecução dos Objetivos Previstos no Programa Nacional de Banda Larga - (Dec. 7.175 de 12/05/2010)'),
array('ticker'=>'CGAS3','name'=>'COMGAS ON','main_activity'=>'Setor de Atividade: Utilidade Pública: Distribuição de Gás Natural Canalizado.'),
array('ticker'=>'GOVE11','name'=>'IT NOW IGCT CI','main_activity'=>''),
array('ticker'=>'BRAX11','name'=>'ISHARES BRAX CI','main_activity'=>''),
array('ticker'=>'MSCD34','name'=>'MASTERCARD DRN','main_activity'=>''),
array('ticker'=>'SDIL11','name'=>'FII SDI LOG','main_activity'=>''),
array('ticker'=>'BPFF11','name'=>'FII ABSOLUTO','main_activity'=>''),
array('ticker'=>'CTNM4','name'=>'COTEMINAS PN','main_activity'=>'Holding'),
array('ticker'=>'LIQO3','name'=>'LIQ','main_activity'=>'A Liq É Uma das Maiores Empresas Brasileiras Especializadas de Forma Abrangente na Gestão do Relacionamento com o Consumidor. Atuando de Forma Consultiva e Personalizada.'),
array('ticker'=>'BOEI34','name'=>'BOEING DRN','main_activity'=>''),
array('ticker'=>'BEES3','name'=>'BANESTES ON','main_activity'=>'Intermediação Financeira Inerente Aos Bancos Múltiplos por Meio das Carteiras Autorizadas. Inclusive Operações de Câmbio.'),
array('ticker'=>'AMGN34','name'=>'AMGEN DRN','main_activity'=>''),
array('ticker'=>'AGCX11','name'=>'FII AG CAIXA','main_activity'=>''),
array('ticker'=>'ONEF11','name'=>'FII THE ONE','main_activity'=>''),
array('ticker'=>'JPMC34','name'=>'JPMORGAN DRN','main_activity'=>''),
array('ticker'=>'FAED11','name'=>'FII ANH EDUC','main_activity'=>''),
array('ticker'=>'TEXA34','name'=>'TEXAS INC DRN','main_activity'=>''),
array('ticker'=>'LMTB34','name'=>'LOCKHEED DRN','main_activity'=>''),
array('ticker'=>'MACY34','name'=>'MACY S DRN','main_activity'=>''),
array('ticker'=>'ACNB34','name'=>'ACCENTURE DRN','main_activity'=>''),
array('ticker'=>'PQDP11','name'=>'FII D PEDRO','main_activity'=>''),
array('ticker'=>'USBC34','name'=>'US BANCORP DRN','main_activity'=>''),
array('ticker'=>'HONB34','name'=>'HONEYWELL DRN','main_activity'=>''),
array('ticker'=>'GEPA4','name'=>'GER PARANAP PN','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'CXRI11','name'=>'FII CX RBRAV','main_activity'=>''),
array('ticker'=>'MNDL3','name'=>'MUNDIAL ON','main_activity'=>'Componentes Diversos para Indústria de Calçados Confecções. Artigos de Cuidados Pessoais e de Cultelaria.'),
array('ticker'=>'SLBG34','name'=>'SCHLUMBERGER DRN','main_activity'=>''),
array('ticker'=>'VVAR3','name'=>'VIAVAREJO ON','main_activity'=>''),
array('ticker'=>'DOMC11','name'=>'FII DOMO','main_activity'=>''),
array('ticker'=>'BGIP4','name'=>'BANESE PN','main_activity'=>''),
array('ticker'=>'DEAI34','name'=>'DELTA DRN','main_activity'=>''),
array('ticker'=>'VIVR3','name'=>'VIVER ON','main_activity'=>'Incorporadora e Construtora Presente em Todas as Regiões do País e com Foco de Atuação no Mercado Residencial. Particularmente Nos Segmentos de Média e Baixa Renda.'),
array('ticker'=>'VISA34','name'=>'VISA INC DRN','main_activity'=>''),
array('ticker'=>'BMYB34','name'=>'BRISTOLMYERS DRN','main_activity'=>''),
array('ticker'=>'BSEV3','name'=>'BIOSEV ON','main_activity'=>'Produção. Processamento. Industrialização. Distribuição e Comercialização de Cana?de-Açúcar e Seus Derivados. Açúcar e Etanol; entre Outros.'),
array('ticker'=>'CMCS34','name'=>'COMCAST DRN','main_activity'=>''),
array('ticker'=>'DHER34','name'=>'DANAHER CORP DRN','main_activity'=>''),
array('ticker'=>'UTEC34','name'=>'UNITED TECH DRN','main_activity'=>''),
array('ticker'=>'NSLU11','name'=>'FII LOURDES','main_activity'=>''),
array('ticker'=>'VVAR4','name'=>'VIAVAREJO PN','main_activity'=>''),
array('ticker'=>'MCDC34','name'=>'MCDONALDS DRN','main_activity'=>''),
array('ticker'=>'LLIS3','name'=>'LE LIS BLANC ON','main_activity'=>'(a) Confecção de Produtos em Geral. Através de Terceiros; (b) Importação e Exportação; (c) Exploração de Comércio e Indústria de Confecção de Produtos em Geral.'),
array('ticker'=>'BAZA3','name'=>'AMAZONIA ON','main_activity'=>''),
array('ticker'=>'GILD34','name'=>'GILEAD DRN','main_activity'=>''),
array('ticker'=>'FDXB34','name'=>'FEDEX CORP DRN','main_activity'=>''),
array('ticker'=>'TRXL11','name'=>'FII TRX LOG','main_activity'=>''),
array('ticker'=>'QCOM34','name'=>'QUALCOMM DRN','main_activity'=>''),
array('ticker'=>'TIET3','name'=>'AES TIETE E ON','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'MGFF11','name'=>'FII MOGNO','main_activity'=>''),
array('ticker'=>'BPHA3','name'=>'BR PHARMA ON','main_activity'=>'Empresa do Setor de Varejo Farmacêutico.'),
array('ticker'=>'GDBR34','name'=>'GEN DYNAMICS DRN','main_activity'=>''),
array('ticker'=>'AXPB34','name'=>'AMERICAN EXP DRN','main_activity'=>''),
array('ticker'=>'KMBB34','name'=>'KIMBERLY CL DRN','main_activity'=>''),
array('ticker'=>'CBOP11','name'=>'FII C BRANCO','main_activity'=>''),
array('ticker'=>'PNVL3','name'=>'DIMED ON','main_activity'=>'Comercio Atacadista e Varejista de Medicamentos e Produtos de Perfumaria e Toucador'),
array('ticker'=>'CPRE3','name'=>'CPFL RENOVAV ON','main_activity'=>'Geração de Energias Renováveis.'),
array('ticker'=>'BOBR4','name'=>'BOMBRIL PN','main_activity'=>'1080'),
array('ticker'=>'OUJP11','name'=>'FII OURI JPP','main_activity'=>''),
array('ticker'=>'GMCO34','name'=>'GENERAL MOT DRN','main_activity'=>''),
array('ticker'=>'CGRA3','name'=>'GRAZZIOTIN ON','main_activity'=>'Comércio Varejista de Vesturio e Bazar.'),
array('ticker'=>'BBRC11','name'=>'FII BB CORP','main_activity'=>''),
array('ticker'=>'TGAR11B','name'=>'FII TG ATIVO','main_activity'=>''),
array('ticker'=>'COLG34','name'=>'COLGATE DRN','main_activity'=>''),
array('ticker'=>'TWXB34','name'=>'TIME WARNER DRN','main_activity'=>''),
array('ticker'=>'JRDM11','name'=>'FII SHOPJSUL','main_activity'=>''),
array('ticker'=>'EKTR4','name'=>'ELEKTRO PN','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'RBGS11','name'=>'FII RB GSB I','main_activity'=>''),
array('ticker'=>'ECOO11','name'=>'ISHARES ECOO CI','main_activity'=>''),
array('ticker'=>'BLAK34','name'=>'BLACKROCK DRN','main_activity'=>''),
array('ticker'=>'SAPR3','name'=>'SANEPAR ON','main_activity'=>'Exploração de Serviços Públicos e de Sistemas Privados de Abastecimento de Água. de Coleta. Remoção e Destinação Final de Efluentes e Resíduos Sólidos Domésticos e Industriais e Seus Subprodutos.'),
array('ticker'=>'EXXO34','name'=>'EXXON MOBIL DRN','main_activity'=>''),
array('ticker'=>'RBRD11','name'=>'FII RB II','main_activity'=>''),
array('ticker'=>'MDLZ34','name'=>'MONDELEZ INT DRN','main_activity'=>''),
array('ticker'=>'AETB34','name'=>'AETNA INC DRN','main_activity'=>''),
array('ticker'=>'GOGL35','name'=>'ALPHABET DRN','main_activity'=>''),
array('ticker'=>'FMXB34','name'=>'FEMSA DRN','main_activity'=>''),
array('ticker'=>'BONY34','name'=>'BNY MELLON DRN','main_activity'=>''),
array('ticker'=>'CRIV3','name'=>'ALFA FINANC ON','main_activity'=>'A Sociedade Tem por Objeto A Prática de Todas as Operações de Crédito. Financiamento e Investimentos Permitidas pelas Leis e Regulamento Aplicáveis à Espécie.'),
array('ticker'=>'RBBV11','name'=>'FII JHSF FBV','main_activity'=>''),
array('ticker'=>'HAGA4','name'=>'HAGA S/A PN','main_activity'=>'Industria Metalúrgica - Fab. de Fechaduras P/Construção Civil'),
array('ticker'=>'WALM34','name'=>'WAL MART DRN','main_activity'=>''),
array('ticker'=>'CLGN34','name'=>'CELGENE CORP DRN','main_activity'=>''),
array('ticker'=>'HCRI11','name'=>'FII CRIANCA','main_activity'=>''),
array('ticker'=>'BBYY34','name'=>'BEST BUY DRN','main_activity'=>''),
array('ticker'=>'REDE3','name'=>'REDE ENERGIA ON','main_activity'=>'Participação em Outras Empresas (a Rede Energia Participações É Uma Holding)'),
array('ticker'=>'CATP34','name'=>'CATERPILLAR DRN','main_activity'=>''),
array('ticker'=>'PNVL4','name'=>'DIMED PN','main_activity'=>'Comercio Atacadista e Varejista de Medicamentos e Produtos de Perfumaria e Toucador'),
array('ticker'=>'TGTB34','name'=>'TARGET CORP DRN','main_activity'=>''),
array('ticker'=>'ESRX34','name'=>'EXPRESCRIPTS DRN','main_activity'=>''),
array('ticker'=>'BMEB4','name'=>'MERC BRASIL PN','main_activity'=>'Finanças. Banco Múltiplo'),
array('ticker'=>'DUKB34','name'=>'DUKE ENERGY DRN','main_activity'=>''),
array('ticker'=>'KLBN3','name'=>'KLABIN S/A ON','main_activity'=>'Empresa Brasileira de Base Florestal. Produtora de Papéis e Cartões para Embalagens. Embalagens de Papelão Ondulado e Sacos Industriais. Além de Ser Recicladora e Produtora de Toras para Serrarias.'),
array('ticker'=>'RNEW4','name'=>'RENOVA PN','main_activity'=>'Geração de Energia por Meio de Fontes Renováveis.'),
array('ticker'=>'CESP3','name'=>'CESP ON','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'FSLR34','name'=>'FIRST SOLAR DRN','main_activity'=>''),
array('ticker'=>'PTNT4','name'=>'PETTENATI PN','main_activity'=>'Fabricação de Tecidos Acabados em Malha Circular. Fabricação de Confecções do Vestuário'),
array('ticker'=>'EBAY34','name'=>'EBAY DRN','main_activity'=>''),
array('ticker'=>'CVSH34','name'=>'CVS HEALTH DRN','main_activity'=>''),
array('ticker'=>'MMXM3','name'=>'MMX MINER ON','main_activity'=>'Mineração de Minério de Ferro'),
array('ticker'=>'FIIP11B','name'=>'FII RB CAP I','main_activity'=>''),
array('ticker'=>'SSFO34','name'=>'SALESFORCE DRN','main_activity'=>''),
array('ticker'=>'CHVX34','name'=>'CHEVRON DRN','main_activity'=>''),
array('ticker'=>'TCNO4','name'=>'TECNOSOLO PN','main_activity'=>''),
array('ticker'=>'SCHW34','name'=>'SCHWAB DRN','main_activity'=>''),
array('ticker'=>'INEP4','name'=>'INEPAR PN','main_activity'=>'Fabricação de Equipamentos e Sistemas Elétricos . Fabricação de Torres e Acessórios para Transmissão de Energia e Telecomunicações. Fabricação de Bens de Capital e Sitemas Industriais sob Encomenda.'),
array('ticker'=>'BMEB3','name'=>'MERC BRASIL ON','main_activity'=>'Finanças. Banco Múltiplo'),
array('ticker'=>'MSBR34','name'=>'MORGAN STAN DRN','main_activity'=>''),
array('ticker'=>'SHPH11','name'=>'FII HIGIENOP','main_activity'=>''),
array('ticker'=>'EDFO11B','name'=>'FII OURINVES','main_activity'=>''),
array('ticker'=>'MNPR3','name'=>'MINUPAR ON','main_activity'=>'Criação. Abate Industrialização e Comercialização de Carnes e Produtos Derivados de Aves e Suinos; Importação e Exportação; Prestação de Serviços A Terceiros e Partipação em Outras Empresas'),
array('ticker'=>'BMIN4','name'=>'MERC INVEST PN','main_activity'=>'Investimentos / Financiamentos'),
array('ticker'=>'ABBV34','name'=>'ABBVIE DRN','main_activity'=>''),
array('ticker'=>'BBVJ11','name'=>'FII C JARDIM','main_activity'=>''),
array('ticker'=>'AIGB34','name'=>'AIG GROUP DRN','main_activity'=>''),
array('ticker'=>'CEGR3','name'=>'CEG ON','main_activity'=>'Distribuição de Gás Natural na Região Metropolitana do Estado do Rio de Janeiro.'),
array('ticker'=>'TIFF34','name'=>'TIFFANY DRN','main_activity'=>''),
array('ticker'=>'HALI34','name'=>'HALLIBURTON DRN','main_activity'=>''),
array('ticker'=>'MOSC34','name'=>'MOSAIC CO DRN','main_activity'=>''),
array('ticker'=>'AHEB3','name'=>'SPTURIS ON','main_activity'=>'Cessão de Áreas para Eventos'),
array('ticker'=>'TRPL3','name'=>'TRAN PAULIST ON','main_activity'=>'Transmissão de Energia Elétrica'),
array('ticker'=>'EURO11','name'=>'FII EUROPAR','main_activity'=>''),
array('ticker'=>'TFOF11','name'=>'FII TOPFOFII','main_activity'=>''),
array('ticker'=>'GPSI34','name'=>'GAP DRN','main_activity'=>''),
array('ticker'=>'HOME34','name'=>'HOME DEPOT DRN','main_activity'=>''),
array('ticker'=>'CNES11','name'=>'FII CENESP','main_activity'=>''),
array('ticker'=>'FBOK34','name'=>'FACEBOOK DRN','main_activity'=>''),
array('ticker'=>'GEPA3','name'=>'GER PARANAP ON','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'RDES11','name'=>'FII RD ESCRI','main_activity'=>''),
array('ticker'=>'FLMA11','name'=>'FII S F LIMA','main_activity'=>''),
array('ticker'=>'CESP5','name'=>'CESP PNA','main_activity'=>'Geração e Comercialização de Energia Elétrica'),
array('ticker'=>'GPCP3','name'=>'GPC PART ON','main_activity'=>''),
array('ticker'=>'XRXB34','name'=>'XEROX CORP DRN','main_activity'=>''),
array('ticker'=>'RBDS11','name'=>'FII RBRESID2','main_activity'=>''),
array('ticker'=>'ISUS11','name'=>'IT NOW ISE CI','main_activity'=>''),
array('ticker'=>'RIGG34','name'=>'TRANSOCEAN DRN','main_activity'=>''),
array('ticker'=>'ROST34','name'=>'ROSS STORES DRN','main_activity'=>''),
array('ticker'=>'GPIV33','name'=>'GP INVEST DR3','main_activity'=>'Investimentos Alternativos. Principalmente em Private Equity'),
array('ticker'=>'FDMO34','name'=>'FORD MOTORS DRN','main_activity'=>''),
array('ticker'=>'BTTL3','name'=>'BATTISTELLA ON','main_activity'=>'Com.de Caminhões e Ónibus Scania. Seus Acessórios e Prest.serv.assist.técnica; Industrializ.e Com. de Madeiras; Prestação de Serviços sob A Forma de Trading Company; Partic. em Outras Sociedades.'),
array('ticker'=>'OSXB3','name'=>'OSX BRASIL ON','main_activity'=>'Equipamentos e Serviços para A Indústria Offshore de Petróleo e Gás Natural.'),
array('ticker'=>'BBSD11','name'=>'BB ETF SP DV CI','main_activity'=>''),
array('ticker'=>'RCSL4','name'=>'RECRUSUL PN','main_activity'=>'Produção e Comercialização de Equipamentos para Refrigeração Industrial e Unidades de Transportes.'),
array('ticker'=>'CEEB3','name'=>'COELBA ON','main_activity'=>'Serviço Público de Distribuição de Energia Elétrica'),
array('ticker'=>'HBTS5','name'=>'HABITASUL PNA','main_activity'=>''),
array('ticker'=>'CEED3','name'=>'CEEE-D ON','main_activity'=>'Prestação de Serviços de Natureza Pública ou Privada. no Setor de Distribuição de Energiaelétrica.'),
array('ticker'=>'PFIZ34','name'=>'PFIZER DRN','main_activity'=>''),
array('ticker'=>'PRSV11','name'=>'FII P VARGAS','main_activity'=>''),
array('ticker'=>'IDNT3','name'=>'IDEIASNET ON','main_activity'=>'Aquisição de Participações Diretas e Indiretas em Companhias do Setor de Tecnologia. Mídia e Telecomunicações; e Gestão de Carteiras de Valores Mobiliários e Recursos Próprios e de Terceiros.'),
array('ticker'=>'ATTB34','name'=>'ATT INC DRN','main_activity'=>''),
array('ticker'=>'TRNT11','name'=>'FII TORRE NO','main_activity'=>''),
array('ticker'=>'FIXX11','name'=>'FII FATORFIX','main_activity'=>''),
array('ticker'=>'PINE4','name'=>'PINE PN','main_activity'=>'Banco de Atacado Focado no Relacionamento de Longo Prazo com Clientes de Grande Porte e Investidores. Oferece Crédito. Produtos de Hedging. Mercado de Capitais. Serviços de Assessoria Financeira.'),
array('ticker'=>'CXCE11B','name'=>'FII CX CEDAE','main_activity'=>''),
array('ticker'=>'XTED11','name'=>'FII TRXE COR','main_activity'=>''),
array('ticker'=>'UBSR11','name'=>'FII UBS (BR)','main_activity'=>''),
array('ticker'=>'PLAS3','name'=>'PLASCAR PART ON','main_activity'=>'Participação em Outras Empresas'),
array('ticker'=>'FRIO3','name'=>'METALFRIO ON','main_activity'=>'Fabricação e Comercialiazação de Geladeiras e Similares. de Máquinas de Vendas Automáticas. Componentes e Peças'),
array('ticker'=>'WUNI34','name'=>'WESTERNUNION DRN','main_activity'=>''),
array('ticker'=>'KHCB34','name'=>'KRAFT HEINZ DRN','main_activity'=>''),
array('ticker'=>'ITLC34','name'=>'INTEL DRN','main_activity'=>''),
array('ticker'=>'WFCO34','name'=>'WELLS FARGO DRN','main_activity'=>''),
array('ticker'=>'CRIV4','name'=>'ALFA FINANC PN','main_activity'=>'A Sociedade Tem por Objeto A Prática de Todas as Operações de Crédito. Financiamento e Investimentos Permitidas pelas Leis e Regulamento Aplicáveis à Espécie.'),
array('ticker'=>'WPLZ11B','name'=>'FII W PLAZA','main_activity'=>''),
array('ticker'=>'TMOS34','name'=>'THERMFISCHER DRN','main_activity'=>''),
array('ticker'=>'ALPA3','name'=>'ALPARGATAS ON','main_activity'=>'Indústria e Comércio de Calçados e Artigos Esportivos'),
array('ticker'=>'MSPA3','name'=>'MELHOR SP ON','main_activity'=>''),
array('ticker'=>'BNFS11','name'=>'FII BANRISUL','main_activity'=>''),
array('ticker'=>'CPLE5','name'=>'COPEL PNA','main_activity'=>'Geração. Transmissão. Comercialização e Distribuição de Energia Elétrica'),
array('ticker'=>'TAEE4','name'=>'TAESA PN','main_activity'=>'Transmissão de Energia Elétrica.'),
array('ticker'=>'LBRN34','name'=>'L BRANDS DRN','main_activity'=>''),
array('ticker'=>'MMMC34','name'=>'3M DRN','main_activity'=>''),
array('ticker'=>'ARMT34','name'=>'ARCELOR DRN','main_activity'=>''),
array('ticker'=>'CTXT11','name'=>'FII C TEXTIL','main_activity'=>''),
array('ticker'=>'VERZ34','name'=>'VERIZON DRN','main_activity'=>''),
array('ticker'=>'MOAR3','name'=>'MONT ARANHA ON','main_activity'=>'Holding - Participação Societária'),
array('ticker'=>'ORCL34','name'=>'ORACLE DRN','main_activity'=>''),
array('ticker'=>'ABTT34','name'=>'ABBOTT DRN','main_activity'=>''),
array('ticker'=>'METB34','name'=>'METLIFE INC DRN','main_activity'=>''),
array('ticker'=>'RNDP11','name'=>'FII BB R PAP','main_activity'=>''),
array('ticker'=>'RDNI3','name'=>'RODOBENSIMOB ON','main_activity'=>'(i) A Compra e Venda de Imóveis; (ii) o Desmembramento ou Loteamento de Terrenos; (iii) A Incorporação Imobiliária ou Construção de Imóveis Destinados à Venda; (iv) A Prestação de Serviços A Terceiros'),
array('ticker'=>'VLOL11','name'=>'FII OLIMPIA','main_activity'=>''),
array('ticker'=>'GEOO34','name'=>'GE DRN','main_activity'=>''),
array('ticker'=>'EEEL3','name'=>'CEEE-GT ON','main_activity'=>'Geração e Transmissão de Energia Elétrica'),
array('ticker'=>'CSAB3','name'=>'SEG AL BAHIA ON','main_activity'=>'Companhia de Seguros'),
array('ticker'=>'CSCO34','name'=>'CISCO DRN','main_activity'=>''),
array('ticker'=>'COCA34','name'=>'COCA COLA DRN','main_activity'=>''),
array('ticker'=>'CEOC11','name'=>'FII CEO CCP','main_activity'=>''),
array('ticker'=>'ECPR3','name'=>'ENCORPAR ON','main_activity'=>'Holding'),
array('ticker'=>'PEAB3','name'=>'PAR AL BAHIA ON','main_activity'=>'Participações em Outras Sociedades. na Qualidade de Sócia E/ou Quotista e Administração de Bens Próprios'),
array('ticker'=>'LILY34','name'=>'LILLY DRN','main_activity'=>''),
array('ticker'=>'PLRI11','name'=>'FII POLO I','main_activity'=>''),
array('ticker'=>'BAHI3','name'=>'BAHEMA ON','main_activity'=>'Participação em Outras Sociedades'),
array('ticker'=>'EMAE4','name'=>'EMAE PN','main_activity'=>'Produção de Energia Elétrica'),
array('ticker'=>'CEBR6','name'=>'CEB PNB','main_activity'=>'Holding/Geração e Distribuição de Energia Elétrica'),
array('ticker'=>'UPAC34','name'=>'UNIONPACIFIC DRN','main_activity'=>''),
array('ticker'=>'IDVL4','name'=>'INDUSVAL PN','main_activity'=>'Banco Múltiplo que Concentra Seus Negócios em Produtos de Crédito Corporativo. em Moeda Nacional e Estrangeira. Bem como Produtos de Repasse. Tesouraria e Serviço de Assessoria Financeira A Empresas.'),
array('ticker'=>'FLRP11','name'=>'FII FLORIPA','main_activity'=>''),
array('ticker'=>'JPPC11','name'=>'FII JPP CAPI','main_activity'=>''),
array('ticker'=>'THRA11','name'=>'FII BM THERA','main_activity'=>''),
array('ticker'=>'BDLL4','name'=>'BARDELLA PN','main_activity'=>'Bens de Capital que Fornece Produtos e Serviços para os Segmentos de Metalurgia. Movimentação de Materiais. Óleo e Gás. Energia e Aços Laminados e Trefilados. para os Mercados Nacional e Internacional'),
array('ticker'=>'USSX34','name'=>'US STEEL DRN','main_activity'=>''),
array('ticker'=>'WLMM3','name'=>'WLM IND COM ON','main_activity'=>'Comércio A Varejo e por Atacado de Caminhões. Automóveis. Camionetas e Utilitários Novos e Usados.holding de Instituições Não-Financeira.'),
array('ticker'=>'IGBR3','name'=>'IGB S/A ON','main_activity'=>'Eletroeletrónica'),
array('ticker'=>'TWTR34','name'=>'TWITTER DRN','main_activity'=>''),
array('ticker'=>'PEAB4','name'=>'PAR AL BAHIA PN','main_activity'=>'Participações em Outras Sociedades. na Qualidade de Sócia E/ou Quotista e Administração de Bens Próprios'),
array('ticker'=>'FBMC4','name'=>'FIBAM PN','main_activity'=>'Fabricação de Peças e Acessórios para Veículos Automotores Tais como Parafusos. Porcas. Arruelas. Roscas e Similares.'),
array('ticker'=>'CCPR3','name'=>'CYRE COM-CCP ON','main_activity'=>'Incorporação de Empreendimentos Imobiliários'),
array('ticker'=>'EALT4','name'=>'ACO ALTONA PN','main_activity'=>'Fundição de Ferro e Aço'),
array('ticker'=>'BRSR5','name'=>'BANRISUL PNA','main_activity'=>'Banco Múltiplo Atuante nas Carteiras Comercial. Crédito. Financiamento e Investimento. Crédito Imobiliário. Desenvolvimento e Arrendamento Mercantil e de Investimentos.'),
array('ticker'=>'RPAD6','name'=>'ALFA HOLDING PNB','main_activity'=>''),
array('ticker'=>'CLSC3','name'=>'CELESC ON','main_activity'=>'Holding do Setor de Energia'),
array('ticker'=>'MATB11','name'=>'IT NOW IMAT CI','main_activity'=>''),
array('ticker'=>'UPSS34','name'=>'UPS DRN','main_activity'=>''),
array('ticker'=>'ELEK4','name'=>'ELEKEIROZ PN','main_activity'=>'Industrialização e Comercialização de Produtos Químicos'),
array('ticker'=>'DASA3','name'=>'DASA ON','main_activity'=>'Análises Clínicas e Medicina Diagnóstica'),
array('ticker'=>'RSUL4','name'=>'RIOSULENSE PN','main_activity'=>'Industria Mecâno Metalúrgica'),
array('ticker'=>'BRIV3','name'=>'ALFA INVEST ON','main_activity'=>'A Prática de Todas as Operações Permitidas à Sociedade da Espécie pelas Disposições Legais e Regulamentares que Então Vigorem. Inclusive as de Câmbio. Mas Excetuadas Outras que Dependem de Autoriazaçã'),
array('ticker'=>'OUCY11','name'=>'FII OURICYRE','main_activity'=>''),
array('ticker'=>'INEP3','name'=>'INEPAR ON','main_activity'=>'Fabricação de Equipamentos e Sistemas Elétricos . Fabricação de Torres e Acessórios para Transmissão de Energia e Telecomunicações. Fabricação de Bens de Capital e Sitemas Industriais sob Encomenda.'),
array('ticker'=>'BMLC11B','name'=>'FII BMBRC LC','main_activity'=>''),
array('ticker'=>'CTSA3','name'=>'SANTANENSE ON','main_activity'=>'Indústria Têxtil'),
array('ticker'=>'TEKA3','name'=>'TEKA ON','main_activity'=>'Fabricação de Artigos de Cama. Mesa e Banho'),
array('ticker'=>'GSGI34','name'=>'GOLDMANSACHS DRN','main_activity'=>''),
array('ticker'=>'SLED3','name'=>'SARAIVA LIVR ON','main_activity'=>'Edição. Indústria e Comércio de Livros e Publicações em Geral.'),
array('ticker'=>'RCSL3','name'=>'RECRUSUL ON','main_activity'=>'Produção e Comercialização de Equipamentos para Refrigeração Industrial e Unidades de Transportes.'),
array('ticker'=>'JBDU4','name'=>'J B DUARTE PN','main_activity'=>'I - Exploração Industrial e Comercial. Exp. e Imp de Produtos Alimenticios; Ii - Exploração Industrial e Acondicionamento de Produtos Alimenticios; Iii - Particip em Outras Sociedades.'),
array('ticker'=>'ECPR4','name'=>'ENCORPAR PN','main_activity'=>'Holding'),
array('ticker'=>'GPRO34','name'=>'GOPRO DRN','main_activity'=>''),
array('ticker'=>'HPQB34','name'=>'HP COMPANY DRN','main_activity'=>''),
array('ticker'=>'ADHM3','name'=>'ADVANCED-DH ON','main_activity'=>'Prestação de Serv. de Medicina Preventiva; Comércio. Distribuição. Importação e Exportação de Kits de Teste Laboratorial; Intermediação de Neg.; Licenciamento de Marcas e Franquias; Etc.'),
array('ticker'=>'CRPG3','name'=>'CRISTAL ON','main_activity'=>''),
array('ticker'=>'BNBR3','name'=>'NORD BRASIL ON','main_activity'=>'Banco Múltiplo com Carteira Comercial'),
array('ticker'=>'EKTR3','name'=>'ELEKTRO ON','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'RNEW3','name'=>'RENOVA ON','main_activity'=>'Geração de Energia por Meio de Fontes Renováveis.'),
array('ticker'=>'BIOM3','name'=>'BIOMM ON','main_activity'=>'Licenciamento de Tecnologia para Produção de Proteínas Terapêuticas Recombinantes. Especialmente Insulina.'),
array('ticker'=>'MGEL4','name'=>'MANGELS INDL PN','main_activity'=>'Produção de Relaminados. Trefilados e Perfilados de Aço. Exceto Arames.'),
array('ticker'=>'CRPG6','name'=>'CRISTAL PNB','main_activity'=>''),
array('ticker'=>'CAMB4','name'=>'CAMBUCI PN','main_activity'=>''),
array('ticker'=>'JCPC34','name'=>'JC PENNEY DRN','main_activity'=>''),
array('ticker'=>'DOHL4','name'=>'DOHLER PN','main_activity'=>'Fabricação de Artefatos Têxteis para Uso Doméstico'),
array('ticker'=>'HETA3','name'=>'HERCULES ON','main_activity'=>'Fabricação e A Comercialização de Toda A Espécie de Talheres e Outros Artigos de Mesa para Uso Doméstico. Artigos de Adorno. Beleza. Higiene. Móveis. Material Escolar. de Escritório e Profissional.'),
array('ticker'=>'CXTL11','name'=>'FII CX TRX','main_activity'=>''),
array('ticker'=>'CBEE3','name'=>'AMPLA ENERG ON','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'TAEE3','name'=>'TAESA ON','main_activity'=>'Transmissão de Energia Elétrica.'),
array('ticker'=>'COPH34','name'=>'COPHILLIPS DRN','main_activity'=>''),
array('ticker'=>'CASN4','name'=>'CASAN PN','main_activity'=>'Atuar como Instituição Integrante do Sistema de Saneamento Básico e de Saúde do Estado de Santa Catarina Através dos Serviços de Captação. Tratamento e Distribuição de Água e Tratamento de Esgoto.'),
array('ticker'=>'BAUH4','name'=>'EXCELSIOR PN','main_activity'=>''),
array('ticker'=>'SOND5','name'=>'SONDOTECNICA PNA','main_activity'=>'Consultoria Técnica e Económica na Área de Engenharia e Arquitetura'),
array('ticker'=>'HOOT4','name'=>'HOTEIS OTHON PN','main_activity'=>'Prestação de Serviços na Indústria Hoteleira'),
array('ticker'=>'LIPR3','name'=>'ELETROPAR ON','main_activity'=>'A Eletropar Tem por Objeto Social Principal A Participação no Capital Social da Eletropaulo - Eletricidade de São Paulo S.a.. Concessionária de Serviços Pub. de Energia Elét.. e de Outras Sociedades.'),
array('ticker'=>'SCPF11','name'=>'FII SCP','main_activity'=>''),
array('ticker'=>'HGCR12','name'=>'FII CSHG CRI','main_activity'=>''),
array('ticker'=>'RPMG3','name'=>'PET MANGUINH ON','main_activity'=>'Fabricação de Produtos de Refino de Petróleo.'),
array('ticker'=>'CEBR3','name'=>'CEB ON','main_activity'=>'Holding/Geração e Distribuição de Energia Elétrica'),
array('ticker'=>'BCIA11','name'=>'FII BCIA','main_activity'=>''),
array('ticker'=>'TOYB4','name'=>'TECTOY PN','main_activity'=>'Industr/Com.brinquedos. Jogos Eletron. e Entretenimento'),
array('ticker'=>'ELET5','name'=>'ELETROBRAS PNA','main_activity'=>'Empresa Holding de Geração. Transmissão e Distribuição de Energia'),
array('ticker'=>'BRKM6','name'=>'BRASKEM PNB','main_activity'=>'(1) Produção de Produtos Químicos e Petroquímicos Básicos. Resinas Termoplásticas. Utilidades e Energia Elétrica; (2) Prestação de Serviços Industriais; e (3) Participação em Outras Sociedades.'),
array('ticker'=>'GSHP3','name'=>'GENERALSHOPP ON','main_activity'=>'Administração de Shopping Centers'),
array('ticker'=>'CREM3','name'=>'CREMER ON','main_activity'=>'Indústria e Comércio de Produtos Têxteis (Tecidos e Não Tecidos). Cirúrgicos. Hospitalares.adesivos Cirúrgicos e Industriais. Cosméticos. de Perfumaria e Higiene. Comércio de Medicamentos. Saneantes'),
array('ticker'=>'BEES4','name'=>'BANESTES PN','main_activity'=>'Intermediação Financeira Inerente Aos Bancos Múltiplos por Meio das Carteiras Autorizadas. Inclusive Operações de Câmbio.'),
array('ticker'=>'AELP3','name'=>'AES ELPA ON','main_activity'=>'O Objeto Social da Companhia É A Participação em Outras Sociedades como Quotista. Acionista ou Membro de Consórcio.'),
array('ticker'=>'BGIP3','name'=>'BANESE ON','main_activity'=>''),
array('ticker'=>'BMKS3','name'=>'BIC MONARK ON','main_activity'=>'Fabricação e Comercialização de Bicicletas'),
array('ticker'=>'MTIG4','name'=>'METAL IGUACU PN','main_activity'=>'Fábrica de Embalagens Metálicas para Alimentos'),
array('ticker'=>'ESTR4','name'=>'ESTRELA PN','main_activity'=>'Fabricação de Brinquedos e Jogos Recreativos'),
array('ticker'=>'PATI3','name'=>'PANATLANTICA ON','main_activity'=>'Industrialização e Comercialização de Aços Planos.'),
array('ticker'=>'ENGI4','name'=>'ENERGISA PN','main_activity'=>'Sociedade de Participações em Outras Empresas. Predominantemente em Distribuidoras de Energia Elétrica.'),
array('ticker'=>'PTNT3','name'=>'PETTENATI ON','main_activity'=>'Fabricação de Tecidos Acabados em Malha Circular. Fabricação de Confecções do Vestuário'),
array('ticker'=>'BSLI4','name'=>'BRB BANCO PN','main_activity'=>'O Brb É Uma Instituição Financeira de Economia Mista. Controlada pelo Governo do Distrito Federal. Organizada sob A Forma de Banco Múltiplo'),
array('ticker'=>'JFEN3','name'=>'JOAO FORTES ON','main_activity'=>'Incorporação e Construção de Imóveis; Execução por Administração de Obras de Construção Civil'),
array('ticker'=>'SNSY5','name'=>'SANSUY PNA','main_activity'=>'Indústria e Comércio de Artefatos Plásticos'),
array('ticker'=>'CTNM3','name'=>'COTEMINAS ON','main_activity'=>'Holding'),
array('ticker'=>'WHRL3','name'=>'WHIRLPOOL ON','main_activity'=>'Fabricação e Comercialização de Eletrodomésticos e Compressores'),
array('ticker'=>'TELB3','name'=>'TELEBRAS ON','main_activity'=>'Consecução dos Objetivos Previstos no Programa Nacional de Banda Larga - (Dec. 7.175 de 12/05/2010)'),
array('ticker'=>'CEED4','name'=>'CEEE-D PN','main_activity'=>'Prestação de Serviços de Natureza Pública ou Privada. no Setor de Distribuição de Energiaelétrica.'),
array('ticker'=>'DRIT11B','name'=>'FII MTGESTAO','main_activity'=>''),
array('ticker'=>'FJTA3','name'=>'FORJA TAURUS ON','main_activity'=>'Indústria e Comércio de Armas'),
array('ticker'=>'CTKA4','name'=>'KARSTEN PN','main_activity'=>'Fabricação. Exportação. Importação e o Comércio Atacadista e Varejista de Fios. Tecidos e Produtos Têxteis em Geral.'),
array('ticker'=>'CGAS11','name'=>'COMGAS PRB','main_activity'=>'Setor de Atividade: Utilidade Pública: Distribuição de Gás Natural Canalizado.'),
array('ticker'=>'FESA3','name'=>'FERBASA ON','main_activity'=>'Fabricação e Comercialização dos Diversos Tipos de Ferroligas'),
array('ticker'=>'REIT11','name'=>'FII REIT RIV','main_activity'=>''),
array('ticker'=>'JSRE12','name'=>'FII JS REAL','main_activity'=>''),
array('ticker'=>'BRGE6','name'=>'ALFA CONSORC PNB','main_activity'=>'A Sociedade Tem por Objeto Social: a) todos e Quaisquer Serviços de Engenharia Permitidos pelas Leis e Regulamentos Aplicáveis à Espécie;b) atuar como Representante. Administradora ou Procurad'),
array('ticker'=>'BSAN33','name'=>'BANSANTANDER DR3','main_activity'=>'Instituição Financeira'),
array('ticker'=>'ATSA11B','name'=>'FII CSHGATSA','main_activity'=>''),
array('ticker'=>'CRDE3','name'=>'CR2 ON','main_activity'=>'Incorporação Imobiliária'),
array('ticker'=>'RAPT3','name'=>'RANDON PART ON','main_activity'=>'Indústria e Comércio de Veíc. Automotores e Rebocados para A Movimentação e o de Transporte de Materiais; de Implem para o Transp Rodoviário e Ferroviário e de Aparelhos Mecânicos. Peças'),
array('ticker'=>'FRTA3','name'=>'POMIFRUTAS ON','main_activity'=>'Pomicultura Produção. Comercialização e Exportação'),
array('ticker'=>'JOPA3','name'=>'JOSAPAR ON','main_activity'=>'Beneficiamento de Arroz e Participações'),
array('ticker'=>'CELP5','name'=>'CELPA PNA','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'CEDO4','name'=>'CEDRO PN','main_activity'=>'Indústria Têxtil'),
array('ticker'=>'FPAB11','name'=>'FII A BRANCA','main_activity'=>''),
array('ticker'=>'PATI4','name'=>'PANATLANTICA PN','main_activity'=>'Industrialização e Comercialização de Aços Planos.'),
array('ticker'=>'CELP3','name'=>'CELPA ON','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'TOYB3','name'=>'TECTOY ON','main_activity'=>'Industr/Com.brinquedos. Jogos Eletron. e Entretenimento'),
array('ticker'=>'ENMT3','name'=>'ENERGISA MT ON','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'ENMT4','name'=>'ENERGISA MT PN','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'ITEC3','name'=>'ITAUTEC ON','main_activity'=>'Participação em Outras Sociedades no País e no Exterior. em Especial Naquelas que Atuam na Fabricação e Comercialização de Equipamentos de Automações Bancária e Comercial e na Prestação de Serviços'),
array('ticker'=>'ELEK3','name'=>'ELEKEIROZ ON','main_activity'=>'Industrialização e Comercialização de Produtos Químicos'),
array('ticker'=>'SULA4','name'=>'SUL AMERICA PN','main_activity'=>'A Sul América S.A. É Uma Sociedade de Participação e Suas Controladas Atuam Nos Setores de Seguros. Previdência Complementar. Administração de Recursos. Capitalização e Assistência à Saúde.'),
array('ticker'=>'JBDU3','name'=>'J B DUARTE ON','main_activity'=>'I - Exploração Industrial e Comercial. Exp. e Imp de Produtos Alimenticios; Ii - Exploração Industrial e Acondicionamento de Produtos Alimenticios; Iii - Particip em Outras Sociedades.'),
array('ticker'=>'BPAC5','name'=>'BTGP BANCO PNA','main_activity'=>'A Companhia e Suas Controladas Formam Um Grupo de Prestação de Serviços Financeiros Sediado no Brasil. Atuando como Banco Múltiplo. com Carteira de Investimento. Nos Termos da Legislação Aplicável.'),
array('ticker'=>'AVON34','name'=>'AVON DRN','main_activity'=>''),
array('ticker'=>'SULA3','name'=>'SUL AMERICA ON','main_activity'=>'A Sul América S.A. É Uma Sociedade de Participação e Suas Controladas Atuam Nos Setores de Seguros. Previdência Complementar. Administração de Recursos. Capitalização e Assistência à Saúde.'),
array('ticker'=>'RBCB11','name'=>'FII RIOBRCIB','main_activity'=>''),
array('ticker'=>'USIM6','name'=>'USIMINAS PNB','main_activity'=>'Venda de Produtos Siderúrgicos. como Chapas Grossas. Laminados A Quente. A Frio. Placas. Galvanizados. entre Outros.'),
array('ticker'=>'WHRL4','name'=>'WHIRLPOOL PN','main_activity'=>'Fabricação e Comercialização de Eletrodomésticos e Compressores'),
array('ticker'=>'SPXI11','name'=>'IT NOW SPXI','main_activity'=>''),
array('ticker'=>'NORD3','name'=>'NORDON MET ON','main_activity'=>'A Sociedade Tem como Atividade Operacional Preponderante A Produção de Bens de Capital Destinados ao Mercado Interno e Externo para os Setores Químico. Petrolífero. Petroquímico. Criogenia. Alimentíci'),
array('ticker'=>'CELP7','name'=>'CELPA PNC','main_activity'=>'Distribuição de Energia Elétrica'),
array('ticker'=>'BALM4','name'=>'BAUMER PN','main_activity'=>'Fabricação Aparelhos e Instrumentos P/ Uso Medico Hospitalar e Ortopedia'),
array('ticker'=>'CEDO3','name'=>'CEDRO ON','main_activity'=>'Indústria Têxtil'),
array('ticker'=>'ENGI3','name'=>'ENERGISA ON','main_activity'=>'Sociedade de Participações em Outras Empresas. Predominantemente em Distribuidoras de Energia Elétrica.'),
array('ticker'=>'BPAC3','name'=>'BTGP BANCO ON','main_activity'=>'A Companhia e Suas Controladas Formam Um Grupo de Prestação de Serviços Financeiros Sediado no Brasil. Atuando como Banco Múltiplo. com Carteira de Investimento. Nos Termos da Legislação Aplicável.'),
array('ticker'=>'EALT3','name'=>'ACO ALTONA ON','main_activity'=>'Fundição de Ferro e Aço'),
array('ticker'=>'PABY11','name'=>'FII PANAMBY','main_activity'=>''),
array('ticker'=>'HETA4','name'=>'HERCULES PN','main_activity'=>'Fabricação e A Comercialização de Toda A Espécie de Talheres e Outros Artigos de Mesa para Uso Doméstico. Artigos de Adorno. Beleza. Higiene. Móveis. Material Escolar. de Escritório e Profissional.'),
array('ticker'=>'DTCY3','name'=>'DTCOM-DIRECT ON','main_activity'=>'Treinamento em Desenvolvimento Profissional e Gerencial'),
array('ticker'=>'AFLT3','name'=>'AFLUENTE T ON','main_activity'=>'Transmissão de Energia Elétrica'),
array('ticker'=>'NVHO11','name'=>'FII NOVOHORI','main_activity'=>''),
array('ticker'=>'SPRI3','name'=>'SPRINGER ON','main_activity'=>'Indústria e Comércio. Importação e Exportação de Eletrodomésticos'),
array('ticker'=>'TEKA4','name'=>'TEKA PN','main_activity'=>'Fabricação de Artigos de Cama. Mesa e Banho'),
array('ticker'=>'MERC4','name'=>'MERC FINANC PN','main_activity'=>'Crédito. Financiamento e Investimentos.'),
array('ticker'=>'WLMM4','name'=>'WLM IND COM PN','main_activity'=>'Comércio A Varejo e por Atacado de Caminhões. Automóveis. Camionetas e Utilitários Novos e Usados.holding de Instituições Não-Financeira.'),
array('ticker'=>'ALUP3','name'=>'ALUPAR ON','main_activity'=>'A Participação em Outras Sociedades Atuantes Nos Setores de Energia e Infra-Estrutura. no Brasil ou no Exterior; A Geração. Transformação. Transporte. A Distribuiçãoe o Comércio de Energia.'),
array('ticker'=>'SPRI5','name'=>'SPRINGER PNA','main_activity'=>'Indústria e Comércio. Importação e Exportação de Eletrodomésticos'),
array('ticker'=>'BRGE12','name'=>'ALFA CONSORC PNF','main_activity'=>'A Sociedade Tem por Objeto Social: a) todos e Quaisquer Serviços de Engenharia Permitidos pelas Leis e Regulamentos Aplicáveis à Espécie;b) atuar como Representante. Administradora ou Procurad'),
array('ticker'=>'CTSA4','name'=>'SANTANENSE PN','main_activity'=>'Indústria Têxtil'),
array('ticker'=>'AZEV4','name'=>'AZEVEDO PN','main_activity'=>'Execução de Obras de Construção Pesada Junto A Orgãos Públicos'),
array('ticker'=>'ALUP4','name'=>'ALUPAR PN','main_activity'=>'A Participação em Outras Sociedades Atuantes Nos Setores de Energia e Infra-Estrutura. no Brasil ou no Exterior; A Geração. Transformação. Transporte. A Distribuiçãoe o Comércio de Energia.'),
array('ticker'=>'RBVO11','name'=>'FII RIOBCRI2','main_activity'=>''),
array('ticker'=>'RANI3','name'=>'CELUL IRANI ON','main_activity'=>'Fabricação de Papel para Embalagem. Embalagens de Papelão Ondulado e Resinas.'),
array('ticker'=>'RANI4','name'=>'CELUL IRANI PN','main_activity'=>'Fabricação de Papel para Embalagem. Embalagens de Papelão Ondulado e Resinas.'),
array('ticker'=>'BRGE8','name'=>'ALFA CONSORC PND','main_activity'=>'A Sociedade Tem por Objeto Social: a) todos e Quaisquer Serviços de Engenharia Permitidos pelas Leis e Regulamentos Aplicáveis à Espécie;b) atuar como Representante. Administradora ou Procurad'),
array('ticker'=>'MAPT4','name'=>'CEMEPE PN','main_activity'=>'Holding'),
array('ticker'=>'BRGE3','name'=>'ALFA CONSORC ON','main_activity'=>'A Sociedade Tem por Objeto Social: a) todos e Quaisquer Serviços de Engenharia Permitidos pelas Leis e Regulamentos Aplicáveis à Espécie;b) atuar como Representante. Administradora ou Procurad'),
array('ticker'=>'BTTL4','name'=>'BATTISTELLA PN','main_activity'=>'Com.de Caminhões e Ónibus Scania. Seus Acessórios e Prest.serv.assist.técnica; Industrializ.e Com. de Madeiras; Prestação de Serviços sob A Forma de Trading Company; Partic. em Outras Sociedades.'),
array('ticker'=>'MWET4','name'=>'WETZEL S/A PN','main_activity'=>'Fabricação de Peças e Acessórios para Sistema Motor de Veículos Automotores'),
array('ticker'=>'WPLZ11','name'=>'FII W PLAZA','main_activity'=>''),
array('ticker'=>'CARE11','name'=>'FII DEA CARE','main_activity'=>''),
array('ticker'=>'FVPQ11','name'=>'FII V PARQUE','main_activity'=>''),
array('ticker'=>'GWIR11','name'=>'FII GWI RI','main_activity'=>''),
array('ticker'=>'RPAD3','name'=>'ALFA HOLDING ON','main_activity'=>''),
array('ticker'=>'TCNO3','name'=>'TECNOSOLO ON','main_activity'=>''),
array('ticker'=>'IDVL3','name'=>'INDUSVAL ON','main_activity'=>'Banco Múltiplo que Concentra Seus Negócios em Produtos de Crédito Corporativo. em Moeda Nacional e Estrangeira. Bem como Produtos de Repasse. Tesouraria e Serviço de Assessoria Financeira A Empresas.'),
array('ticker'=>'PORD11','name'=>'FII POLO CRI','main_activity'=>''),
array('ticker'=>'RDPD11','name'=>'FII BB PAPII','main_activity'=>''),
array('ticker'=>'FMOF11','name'=>'FII MEMORIAL','main_activity'=>''),
array('ticker'=>'BZLI11','name'=>'FII BRREALTY','main_activity'=>''),
array('ticker'=>'FIVN11','name'=>'FII VIDANOVA','main_activity'=>''),
        );
        
        DB::table('stocks')->insert($data);
    }
}

