# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  invest-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: mysql:5.7
    container_name: invest-mysql
    volumes:
      - invest-mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=invest
      - MYSQL_DATABASE=invest
      - MYSQL_USER=invest
      - MYSQL_PASSWORD=invest

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.2-nginx
    container_name: invest-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - mysql